import { CoordinationType } from 'vitessce';

export const PluginCoordinationType = {
  CELL_COLOR_ENCODING_PLUGIN: 'cellColorEncodingPlugin',
  ANCHOR_API_STATE: 'anchorApiState',
  MODEL_API_STATE: 'modelApiState',
  ANCHOR_EDIT_TOOL: 'anchorEditTool', // Is the user lassoing? Either 'lasso' or null.
  ANCHOR_EDIT_MODE: 'anchorEditMode', // Which anchor set is the user currently editing?
  ANCHOR_SET_FOCUS: 'anchorSetFocus', // Which anchor set to focus? (caused by click in Cell Sets)
  ANCHOR_SET_HIGHLIGHT: 'anchorSetHighlight', // Which anchor set to highlight? (caused by hover in Cell Sets)
  EMBEDDING_VISIBLE: 'embeddingVisible', // Whether the embedding is visible (boolean). Intended to be used by the comparison view to determine whether to show the reference or query only.
  EMBEDDING_ENCODING: 'embeddingEncoding', // scatterplot, heatmap, or contour.
  EMBEDDING_LINKS_VISIBLE: 'embeddingLinksVisible', // Whether the lines linking between corresponding query and reference anchor sets are visible (boolean).
  ANCHOR_SET_FILTER: 'anchorSetFilter', // How to sort and filter the list of anchor sets in the Cell Sets view.
  PRESET_BUTTONS_VISIBLE: 'presetButtonsVisible',
  EMBEDDING_LEGENDS_VISIBLE: 'embeddingLegendsVisible',
  DEBUG_CELL_TYPES: 'debugCellTypes',
  EMBEDDING_LINKS_SIZE_ENCODING: 'embeddingLinksSizeEncoding', // null or 'anchorSetScores'
};

export const PluginViewType = {
  QR_COMPARISON_SCATTERPLOT: 'qrComparisonScatterplot',
  QR_CELL_SETS: 'qrCellSets',
  QR_SCORES: 'qrScores',
  QR_STATUS: 'qrStatus',
};

export const PluginFileType = {
  ANNDATA_POLYPHONY_ZARR: 'anndata-polyphony.zarr',
};

export const PLUGIN_DEFAULT_COORDINATION_VALUES = {
  [PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN]: 'cellSetSelection',
  [PluginCoordinationType.ANCHOR_API_STATE]: { iteration: 1, status: 'success', message: null },
  [PluginCoordinationType.MODEL_API_STATE]: { iteration: 1, status: 'success', message: null },
  [PluginCoordinationType.ANCHOR_EDIT_TOOL]: null,
  [PluginCoordinationType.ANCHOR_EDIT_MODE]: null,
  [PluginCoordinationType.ANCHOR_SET_FOCUS]: null,
  [PluginCoordinationType.ANCHOR_SET_HIGHLIGHT]: null,
  [PluginCoordinationType.EMBEDDING_VISIBLE]: true,
  [PluginCoordinationType.EMBEDDING_ENCODING]: 'scatterplot',
  [PluginCoordinationType.EMBEDDING_LINKS_VISIBLE]: false,
  [PluginCoordinationType.ANCHOR_SET_FILTER]: null,
  [PluginCoordinationType.PRESET_BUTTONS_VISIBLE]: true,
  [PluginCoordinationType.EMBEDDING_LEGENDS_VISIBLE]: true,
  [PluginCoordinationType.DEBUG_CELL_TYPES]: false,
  [PluginCoordinationType.EMBEDDING_LINKS_SIZE_ENCODING]: 'anchorSetScores',
};

export const PLUGIN_COMPONENT_COORDINATION_TYPES = {
  [PluginViewType.QR_STATUS]: [
    CoordinationType.DATASET,
    CoordinationType.CELL_HIGHLIGHT,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.CELL_SET_HIGHLIGHT,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.ANCHOR_SET_FILTER,
    PluginCoordinationType.DEBUG_CELL_TYPES,
  ],
  [PluginViewType.QR_COMPARISON_SCATTERPLOT]: [
    CoordinationType.DATASET,
    CoordinationType.EMBEDDING_TYPE,
    CoordinationType.EMBEDDING_ZOOM,
    CoordinationType.EMBEDDING_ROTATION,
    CoordinationType.EMBEDDING_TARGET_X,
    CoordinationType.EMBEDDING_TARGET_Y,
    CoordinationType.EMBEDDING_TARGET_Z,
    CoordinationType.EMBEDDING_CELL_SET_POLYGONS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABELS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABEL_SIZE,
    CoordinationType.EMBEDDING_CELL_RADIUS,
    CoordinationType.EMBEDDING_CELL_RADIUS_MODE,
    CoordinationType.EMBEDDING_CELL_OPACITY,
    CoordinationType.EMBEDDING_CELL_OPACITY_MODE,
    CoordinationType.CELL_FILTER,
    CoordinationType.CELL_HIGHLIGHT,
    CoordinationType.CELL_SET_SELECTION,
    CoordinationType.CELL_SET_HIGHLIGHT,
    CoordinationType.CELL_SET_COLOR,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.GENE_SELECTION,
    CoordinationType.GENE_EXPRESSION_COLORMAP,
    CoordinationType.GENE_EXPRESSION_COLORMAP_RANGE,
    CoordinationType.ADDITIONAL_CELL_SETS,
    PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.EMBEDDING_VISIBLE,
    PluginCoordinationType.EMBEDDING_ENCODING,
    PluginCoordinationType.EMBEDDING_LINKS_VISIBLE,
    PluginCoordinationType.PRESET_BUTTONS_VISIBLE,
    PluginCoordinationType.EMBEDDING_LEGENDS_VISIBLE,
    PluginCoordinationType.DEBUG_CELL_TYPES,
    PluginCoordinationType.EMBEDDING_LINKS_SIZE_ENCODING,
  ],
  [PluginViewType.QR_SUPPORTING_SCATTERPLOT_QUERY]: [
    CoordinationType.DATASET,
    CoordinationType.EMBEDDING_TYPE,
    CoordinationType.EMBEDDING_ZOOM,
    CoordinationType.EMBEDDING_ROTATION,
    CoordinationType.EMBEDDING_TARGET_X,
    CoordinationType.EMBEDDING_TARGET_Y,
    CoordinationType.EMBEDDING_TARGET_Z,
    CoordinationType.EMBEDDING_CELL_SET_POLYGONS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABELS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABEL_SIZE,
    CoordinationType.EMBEDDING_CELL_RADIUS,
    CoordinationType.EMBEDDING_CELL_RADIUS_MODE,
    CoordinationType.EMBEDDING_CELL_OPACITY,
    CoordinationType.EMBEDDING_CELL_OPACITY_MODE,
    CoordinationType.CELL_FILTER,
    CoordinationType.CELL_HIGHLIGHT,
    CoordinationType.CELL_SET_SELECTION,
    CoordinationType.CELL_SET_HIGHLIGHT,
    CoordinationType.CELL_SET_COLOR,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.GENE_SELECTION,
    CoordinationType.GENE_EXPRESSION_COLORMAP,
    CoordinationType.GENE_EXPRESSION_COLORMAP_RANGE,
    CoordinationType.ADDITIONAL_CELL_SETS,
    PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.DEBUG_CELL_TYPES,
  ],
  [PluginViewType.QR_SUPPORTING_SCATTERPLOT_REFERENCE]: [
    CoordinationType.DATASET,
    CoordinationType.EMBEDDING_TYPE,
    CoordinationType.EMBEDDING_ZOOM,
    CoordinationType.EMBEDDING_ROTATION,
    CoordinationType.EMBEDDING_TARGET_X,
    CoordinationType.EMBEDDING_TARGET_Y,
    CoordinationType.EMBEDDING_TARGET_Z,
    CoordinationType.EMBEDDING_CELL_SET_POLYGONS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABELS_VISIBLE,
    CoordinationType.EMBEDDING_CELL_SET_LABEL_SIZE,
    CoordinationType.EMBEDDING_CELL_RADIUS,
    CoordinationType.EMBEDDING_CELL_RADIUS_MODE,
    CoordinationType.EMBEDDING_CELL_OPACITY,
    CoordinationType.EMBEDDING_CELL_OPACITY_MODE,
    CoordinationType.CELL_FILTER,
    CoordinationType.CELL_HIGHLIGHT,
    CoordinationType.CELL_SET_SELECTION,
    CoordinationType.CELL_SET_HIGHLIGHT,
    CoordinationType.CELL_SET_COLOR,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.GENE_SELECTION,
    CoordinationType.GENE_EXPRESSION_COLORMAP,
    CoordinationType.GENE_EXPRESSION_COLORMAP_RANGE,
    CoordinationType.ADDITIONAL_CELL_SETS,
    PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.DEBUG_CELL_TYPES,
  ],
  [PluginViewType.QR_CELL_SETS]: [
    CoordinationType.DATASET,
    CoordinationType.CELL_SET_SELECTION,
    CoordinationType.CELL_SET_HIGHLIGHT,
    CoordinationType.CELL_SET_COLOR,
    CoordinationType.ADDITIONAL_CELL_SETS,
    CoordinationType.GENE_SELECTION,
    CoordinationType.GENE_FILTER,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.EMBEDDING_TYPE,
    PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.EMBEDDING_LINKS_VISIBLE,
    PluginCoordinationType.ANCHOR_SET_FILTER,
    PluginCoordinationType.DEBUG_CELL_TYPES,
  ],
  [PluginViewType.QR_SCORES]: [
    CoordinationType.DATASET,
    CoordinationType.CELL_SET_SELECTION,
    CoordinationType.CELL_SET_HIGHLIGHT,
    CoordinationType.CELL_SET_COLOR,
    CoordinationType.ADDITIONAL_CELL_SETS,
    CoordinationType.GENE_SELECTION,
    CoordinationType.GENE_FILTER,
    CoordinationType.GENE_HIGHLIGHT,
    CoordinationType.EMBEDDING_TYPE,
    PluginCoordinationType.CELL_COLOR_ENCODING_PLUGIN,
    PluginCoordinationType.ANCHOR_API_STATE,
    PluginCoordinationType.MODEL_API_STATE,
    PluginCoordinationType.ANCHOR_EDIT_TOOL,
    PluginCoordinationType.ANCHOR_EDIT_MODE,
    PluginCoordinationType.ANCHOR_SET_FOCUS,
    PluginCoordinationType.ANCHOR_SET_HIGHLIGHT,
    PluginCoordinationType.EMBEDDING_LINKS_VISIBLE,
    PluginCoordinationType.ANCHOR_SET_FILTER,
    PluginCoordinationType.DEBUG_CELL_TYPES,
  ],
};
